Repository microsoft/vscode-copilot-chat, pull requests merged in 2025-08, with the labels that each got.

#331 If chat completion encounters content filtered error, attempt to retry in a way that avoids the filter, using new clear() method to clear the ChatResponseStream
  package.json
  package.nls.json
  src/extension/codeBlocks/node/codeBlockProcessor.ts
  src/extension/inlineChat/vscode-node/inlineChatCommands.ts
  src/extension/intents/test/node/editCodeIntent.spec.ts
  src/extension/linkify/common/responseStreamWithLinkification.ts
  src/extension/prompt/node/chatMLFetcher.ts
  src/extension/prompt/node/pseudoStartStopConversationCallback.ts
  src/extension/prompt/node/test/defaultIntentRequestHandler.spec.ts
  src/extension/prompts/node/inline/workingCopies.ts
  src/extension/test/node/intent.spec.ts
  src/extension/vscode.proposed.chatParticipantAdditions.d.ts
  src/platform/chat/common/commonTypes.ts
  src/platform/configuration/common/configurationService.ts
  src/platform/networking/common/fetch.ts
  src/util/common/chatResponseStreamImpl.ts
  src/util/common/test/mockChatResponseStream.ts
  src/util/common/test/shims/chatTypes.ts
  src/util/common/test/shims/vscodeTypesShim.ts
  src/vscodeTypes.ts
  test/simulation/inlineChatSimulator.ts
Labels: candidate, triage-needed

#412 Add conversation id and message id to relevant events
  src/extension/prompt/node/chatParticipantTelemetry.ts
  src/platform/multiFileEdit/common/multiFileEditQualityTelemetry.ts
  src/platform/networking/node/chatStream.ts
Labels: triage-needed

#459 language context providers: include mandatory fields that exist in latest language context providers API
  src/extension/xtab/node/xtabProvider.ts
  src/platform/inlineCompletions/common/api.ts
Labels: candidate

#461 Fixes #259794: Adapt source field when context provider is called from NES
  src/extension/typescriptContext/vscode-node/languageContextService.ts
Labels: candidate

#475 Fix thinking tool
  package.json
  test/outcome/fetchwebpagetool-toolcalling-panel.json
  test/outcome/findfilestool-toolcalling-panel.json
  test/outcome/notebooks-toolcalling-panel.json
  test/outcome/toolcalling-panel.json
  test/simulation/baseline.json
  test/simulation/cache/layers/8a8e8994-fd12-4f90-96cb-be744ef5e991.sqlite
Labels: candidate

#656 edits: prep for gpt-5 apply-patch exclusive (#650)
  src/extension/intents/node/agentIntent.ts
  src/extension/prompts/node/agent/agentInstructions.tsx
  src/extension/prompts/node/agent/test/__snapshots__/agentPrompt.spec.tsx.snap
  src/platform/configuration/common/configurationService.ts
  src/platform/endpoint/common/chatModelCapabilities.ts
  test/outcome/edit-toolcalling-panel.json
  test/outcome/fetchwebpagetool-toolcalling-panel.json
  test/outcome/findfilestool-toolcalling-panel.json
  test/outcome/notebooks-toolcalling-panel.json
  test/outcome/toolcalling-panel.json
  test/simulation/baseline.json
  test/simulation/cache/layers/f81c77f5-7c05-406e-a639-78804faf786d.sqlite
Labels: candidate

#655 edits: fix add file operation failing with apply_patch
  src/extension/tools/node/applyPatchTool.tsx
Labels: candidate

#694 port PR 665 to simulator
  src/platform/endpoint/test/node/openaiCompatibleEndpoint.ts
Labels: triage-needed

#794 Remove tool calls from `request` type JSON logs exported from chat debug
  src/extension/prompt/vscode-node/requestLoggerImpl.ts
Labels: triage-needed

#819 add sku data to github telemetry
  src/platform/telemetry/common/baseTelemetryService.ts
Labels: triage-needed
